combining items system nearly done, crashing on combining not sure what to do
there's no stack trace for the crash, it just says `thread 'main' panicked at 'error[B0003]: Could not add a component (of type `bag_goblin::game::recipes::Ingredient`) to entity 561v0 because it doesn't exist in this World.'`